# Generated by Django 5.0.6 on 2024-06-25 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria1',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Categoria')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria2',
            fields=[
                ('idCiudad', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Ciudad')),
                ('ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('placa', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Id Vehiculo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('capacidad', models.PositiveIntegerField(verbose_name='Capacidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes', verbose_name='Imagen')),
                ('categoria1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria1', verbose_name='Categoria1')),
                ('categoria2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria2', verbose_name='Categoria2')),
            ],
        ),
    ]
