# Generated by Django 5.0.6 on 2024-07-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_boleta_alter_vehiculo_precio_detalle_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_boleta',
            name='cliente',
            field=models.TextField(default='Sin user', max_length=50, verbose_name='Cliente'),
        ),
    ]
