# Generated by Django 5.0.6 on 2024-07-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_detalle_boleta_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
    ]
